version: "3.9"
services:

  postgres:
    image: postgres:13.1
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
  app:
    depends_on:
      - postgres
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DB?allowPublicKeyRetrieval=true&useSSL=false",
            "spring.datasource.username" : "$POSTGRES_USER",
            "spring.datasource.password" : "$POSTGRES_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQL82Dialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
